AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Trip API RestFull API to manage trips

  '
Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Environment:
      Variables:
        TABLE_NAME:
          Ref: TripTable
        ENDPOINT_OVERRIDE: ''
Resources:
  CreateTripFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://fiap-serveless-34scj/54b4085411130debd9017cfade1f2b71
      Handler: br.com.fiap.handler.CreateTrip::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TripTable
      - Statement:
          Effect: Allow
          Action:
          - s3:*
          Resource: '*'
      Events:
        CreateTrip:
          Type: Api
          Properties:
            Path: /trips
            Method: post
  GetTripByPeriodFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://fiap-serveless-34scj/54b4085411130debd9017cfade1f2b71
      Handler: br.com.fiap.handler.GetTripByPeriod::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TripTable
      Events:
        GetStudyRecordsByPeriod:
          Type: Api
          Properties:
            Path: /trips/findByPeriod
            Method: get
            RequestParameters:
            - method.request.querystring.starts
            - method.request.querystring.ends
  GetTripByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://fiap-serveless-34scj/54b4085411130debd9017cfade1f2b71
      Handler: br.com.fiap.handler.GetTripById::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TripTable
      Events:
        GetTripById:
          Type: Api
          Properties:
            Path: /trips/{id}
            Method: get
  TripTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: trip
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: date
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      - AttributeName: date
        KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
