AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serveless-2016-10-31

Description: >
  Trip API
  RestFull API to manage trips

Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Environment:
      Variables:
        TABLE_NAME: !Ref TripTable
        ENDPOINT_OVERRIDE: ""

Resources:
  CreateTripFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/trip-api-1.0.0-SNAPSHOT-jar-with-dependencies.jar
      Handler: br.com.fiap.handler.CreateTrip::handleRequest
      Runtime: java8
      Events:
        CreateTrip:
          Type: Api
          Properties:
            Path: /trips
            Method: post